name       : gnu-efi
version    : 3.0.2
release    : 1
homepage   : http://sourceforge.net/projects/gnu-efi/
source     :
    - http://downloads.sourceforge.net/project/gnu-efi/gnu-efi-3.0.2.tar.bz2 : 194b580ecdb1fad0e41914845ba064c279afb687855960b58693459e5537b4d7
license    : BSD
summary    : EFI development library
description: |
    Develop EFI applications for ARM-64, ARM-32, x86_64, IA-64 (IPF), and IA-32 (x86) platforms using the GNU toolchain and the EFI development environment.
builddeps  :
build      : |
    %make lib gnuefi inc
install    : |
    %make_install INSTALLROOT="${installdir}" PREFIX="/usr" LIBDIR="%libdir%"
