name       : gnu-efi
version    : 3.0.15
release    : 4
homepage   : http://sourceforge.net/projects/gnu-efi/
source     :
    - http://downloads.sourceforge.net/project/gnu-efi/gnu-efi-3.0.15.tar.bz2 : 931a257b9c5c1ba65ff519f18373c438a26825f2db7866b163e96d1b168f20ea
license    : BSD
summary    : EFI development library
component  : system.boot
emul32     : yes
description: |
    Develop EFI applications for ARM-64, ARM-32, x86_64, IA-64 (IPF), and IA-32 (x86) platforms using the GNU toolchain and the EFI development environment.
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make lib gnuefi inc ARCH=ia32 HOSTARCH=x86_64
    else
        %make lib gnuefi inc
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make_install INSTALLROOT="${installdir}" PREFIX="/usr" LIBDIR="%libdir%" ARCH=ia32 HOSTARCH=x86_64
    else
        %make_install INSTALLROOT="${installdir}" PREFIX="/usr" LIBDIR="%libdir%"
    fi
