name       : gnu-efi
version    : 3.0.2
release    : 2
homepage   : http://sourceforge.net/projects/gnu-efi/
source     :
    - http://downloads.sourceforge.net/project/gnu-efi/gnu-efi-3.0.2.tar.bz2 : 194b580ecdb1fad0e41914845ba064c279afb687855960b58693459e5537b4d7
license    : BSD
summary    : EFI development library
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
description: |
    Develop EFI applications for ARM-64, ARM-32, x86_64, IA-64 (IPF), and IA-32 (x86) platforms using the GNU toolchain and the EFI development environment.
builddeps  :
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make lib gnuefi inc ARCH=ia32 HOSTARCH=x86_64
    else
        %make lib gnuefi inc
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make_install INSTALLROOT="${installdir}" PREFIX="/usr" LIBDIR="%libdir%" ARCH=ia32 HOSTARCH=x86_64
    else
        %make_install INSTALLROOT="${installdir}" PREFIX="/usr" LIBDIR="%libdir%"
    fi
